apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  ## TIP: this determines which version of ArgoCD is installed
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.11/manifests/install.yaml

  ## TIP: if you don't have a default storage class, you may need to set the `spec.storageClassName`
  ## TIP: if you have an HA argocd-repo-server deployment, you will need to make this a ReadWriteMany volume
  - deploykf-plugin/assets-pvc.yaml

patchesStrategicMerge:
  - deploykf-plugin/repo-server-patch.yaml

configMapGenerator:
  - name: argocd-deploykf-plugin
    files:
      - deploykf-plugin/plugin.yaml

images:
  ## TIP: these tags can be used to change the tool versions used by the plugin
  #- name: "docker.io/bitnami/kubectl"
  #  newTag: "1.26.10"
  #- name: "docker.io/alpine/helm"
  #  newTag: "3.12.3"
  #- name: "ghcr.io/deploykf/cli"
  #  newTag: "0.1.2"

  ## TIP: this image is used at runtime by the plugin
  #- name: "docker.io/buildpack-deps"
  #  newTag: "bookworm-curl"
